// client/src/utils/enums.js
export const InjurySeverity = {
  MINOR: 'MINOR',
  MODERATE: 'MODERATE',
  MAJOR: 'MAJOR',
  SEVERE: 'SEVERE',
};

export const BodyPart = {
  HEAD: 'HEAD', NECK: 'NECK', SHOULDER: 'SHOULDER', ARM: 'ARM', ELBOW: 'ELBOW', WRIST: 'WRIST', HAND: 'HAND',
  CHEST: 'CHEST', BACK: 'BACK', ABDOMEN: 'ABDOMEN', HIP: 'HIP', THIGH: 'THIGH', KNEE: 'KNEE', SHIN: 'SHIN', CALF: 'CALF', ANKLE: 'ANKLE', FOOT: 'FOOT',
};

export const VisitType = {
  ROUTINE_CHECKUP: 'ROUTINE_CHECKUP', INJURY_ASSESSMENT: 'INJURY_ASSESSMENT', REHABILITATION: 'REHABILITATION',
  FITNESS_TEST: 'FITNESS_TEST', SPECIALIST_CONSULTATION: 'SPECIALIST_CONSULTATION', EMERGENCY: 'EMERGENCY',
};

export const InjuryType = {
  MUSCLE_STRAIN: 'MUSCLE_STRAIN',
  LIGAMENT_TEAR: 'LIGAMENT_TEAR',
  BONE_FRACTURE: 'BONE_FRACTURE',
  CONCUSSION: 'CONCUSSION',
  BRUISE: 'BRUISE',
  CUT: 'CUT',
  SPRAIN: 'SPRAIN',
  OVERUSE: 'OVERUSE',
  OTHER: 'OTHER',
};

export const InjuryStatus = {
  ACTIVE: 'ACTIVE',
  RECOVERING: 'RECOVERING',
  HEALED: 'HEALED',
  CHRONIC: 'CHRONIC',
};

export const MedicalCaseType = {
  INJURY: 'INJURY',
  ILLNESS: 'ILLNESS',
  SURGERY: 'SURGERY',
  SCREENING: 'SCREENING',
  PREVENTIVE: 'PREVENTIVE',
  OTHER: 'OTHER',
};

export const DataClassification = {
  PUBLIC: 'PUBLIC',
  SENSITIVE: 'SENSITIVE',
  HIGHLY_SENSITIVE: 'HIGHLY_SENSITIVE',
  SPECIAL_CATEGORY: 'SPECIAL_CATEGORY',
};

export const VisibilityLevel = {
  MEDICAL_ONLY: 'MEDICAL_ONLY',
  COACHING_STAFF: 'COACHING_STAFF',
  PLAYER_ACCESS: 'PLAYER_ACCESS',
  TEAM_WIDE: 'TEAM_WIDE',
};

export const ConsentStatus = {
  NOT_REQUESTED: 'NOT_REQUESTED',
  PENDING: 'PENDING',
  GRANTED: 'GRANTED',
  REFUSED: 'REFUSED',
  WITHDRAWN: 'WITHDRAWN',
  EXPIRED: 'EXPIRED',
};

export const LawfulBasis = {
  CONSENT: 'CONSENT',
  CONTRACT: 'CONTRACT',
  LEGAL_OBLIGATION: 'LEGAL_OBLIGATION',
  VITAL_INTERESTS: 'VITAL_INTERESTS',
  LEGITIMATE_INTEREST: 'LEGITIMATE_INTEREST',
  MEDICAL_PURPOSE: 'MEDICAL_PURPOSE',
};
